kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.mediaWiki.appname }}
  labels:
    app: {{ .Values.mediaWiki.appname }}
spec:
  replicas: {{ .Values.mediaWiki.replicCount }}
  selector:
    matchLabels:
      app: {{ .Values.mediaWiki.appname }}
  template:
    metadata:
      name: {{ .Values.mediaWiki.appname }}
      creationTimestamp: null
      labels:
        app: {{ .Values.mediaWiki.appname }}
    spec:
      containers:
        - name: wikiapp
          image: {{ .Values.mediaWiki.wikiImage }}
          ports:
            - containerPort: {{ .Values.mediaWiki.port }}
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
