kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.mediaWiki.servicename }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.mediaWiki.port }}
      targetPort: {{ .Values.mediaWiki.port }}
  selector:
    app: {{ .Values.mediaWiki.appname }}
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
