apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.appname}}
  labels: 
    appname: {{ .Values.mysql.appname}}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      appname: {{ .Values.mysql.appname}}
  template:
    metadata:
      labels: 
        appname: {{ .Values.mysql.appname}}
    spec:
      containers:
      - image: "{{ .Values.mysql.image.name }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        name: {{ template "name" . }}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.persistence.pvcName }}