apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.appnamesvc}}
  labels: 
    appname: {{ .Values.mysql.appnamesvc}}
spec:
  ports:
    - port: 3306
  selector: 
    appname: {{ .Values.mysql.appname}}